version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: library_mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: library_backend
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongodb:27017/library
    depends_on:
      - mongodb
    restart: always

volumes:
  mongodb_data:
